import type { NextPage } from "next";
import Head from "next/head";

import ConnectWallet from '../features/wallet/ConnectWallet';
import SeedPanel from '../features/seed/SeedPanel';

const Seed: NextPage = () => {
  return (
    <>
      <Head>
        <title>Moonapp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SeedPanel />
    </>
  );
};

export default Seed;
